platform :ios, '14.0'
use_frameworks!

target 'Internship2022TeamSzabi' do
  pod 'Firebase/Core', '8.1.0'
  pod 'Firebase/Crashlytics'
  pod 'Firebase/Messaging'
  pod 'Firebase/Analytics'
  pod 'Firebase/Auth'
  pod 'Firebase/Database'
  pod 'Firebase/Firestore'
end
